/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionForm {
  'bankAccountNumber' : string,
  'fatherAadhar' : string,
  'studentEmail' : string,
  'emailId' : string,
  'studentName' : string,
  'subjects' : SubjectSelection,
  'fathersNameAsPerAadhaar' : string,
  'previousSchool' : string,
  'ifscCode' : string,
  'marksObtained' : bigint,
  'dateOfBirth' : bigint,
  'eShikshakoshNumber' : string,
  'passingYear' : bigint,
  'apparNumber' : string,
  'accountHolderName' : string,
  'passingDivision' : PassingDivision,
  'studentPhone' : string,
  'studentPen' : string,
  'motherName' : string,
  'mobileNumber' : string,
  'mothersOccupation' : string,
  'mothersNameAsPerAadhaar' : string,
  'fathersName' : string,
  'bankName' : BankName,
  'mothersName' : string,
  'fathersContact' : string,
  'aadharNumber' : string,
  'fatherName' : string,
  'handicapType' : [] | [string],
  'address' : {
    'policeStation' : string,
    'district' : string,
    'state' : State,
    'village' : string,
    'pinCode' : string,
    'block' : string,
    'postOffice' : string,
  },
  'gender' : Gender,
  'physicallyHandicapped' : boolean,
  'mothersContact' : string,
  'category' : Category,
  'previousRollNo' : string,
  'photo' : [] | [ExternalBlob],
  'guardianDeclaration' : boolean,
  'annualFamilyIncome' : string,
  'handicapPercentage' : [] | [bigint],
  'motherAadhar' : string,
  'fathersOccupation' : string,
  'previousExam' : string,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export type BankName = { 'other' : null } |
  { 'finoPaymentBank' : null } |
  { 'dakshinBiharGraminBank' : null } |
  { 'indianPostPaymentBank' : null } |
  { 'madhyaBiharGraminBank' : null } |
  { 'stateBankOfIndia' : null } |
  { 'unionBankOfIndia' : null } |
  { 'punjabNationalBank' : null };
export type Category = { 'sc' : null } |
  { 'st' : null } |
  { 'bci' : null } |
  { 'ews' : null } |
  { 'bcii' : null } |
  { 'general' : null };
export type Class = { 'class09th' : null } |
  { 'class10th' : null } |
  { 'class11th' : null } |
  { 'class12th' : null };
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type PassingDivision = { 'first' : null } |
  { 'third' : null } |
  { 'second' : null };
export type State = { 'bihar' : null } |
  { 'jharkhand' : null };
export type Stream = { 'arts' : null } |
  { 'commerce' : null } |
  { 'science' : null };
export interface Student {
  'status' : ApplicationStatus,
  'principal' : Principal,
  'form' : [] | [AdmissionForm],
  '_class' : Class,
  'password' : string,
  'name' : string,
  'email' : string,
  'registrationDate' : Time,
}
export interface SubjectSelection {
  'mil' : Array<string>,
  'sil' : Array<string>,
  'stream' : [] | [Stream],
  'extraSubjects' : [] | [string],
  'extra' : [] | [string],
  'compulsory' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  '_class' : Class,
  'name' : string,
  'email' : string,
  'isStudent' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveApplication' : ActorMethod<[string], undefined>,
  'approveApplicationForAdmin' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllApplications' : ActorMethod<[], Array<Student>>,
  'getAllApplicationsForAdmin' : ActorMethod<[string], Array<Student>>,
  'getAllApprovedApplications' : ActorMethod<[], Array<Student>>,
  'getAllPendingApplications' : ActorMethod<[], Array<Student>>,
  'getAllRejectedApplications' : ActorMethod<[], Array<Student>>,
  'getApplicationStatus' : ActorMethod<[string], ApplicationStatus>,
  'getApplicationsSortedByDate' : ActorMethod<[], Array<Student>>,
  'getCallerStudent' : ActorMethod<[], [] | [Student]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getStudent' : ActorMethod<[string], Student>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginStudent' : ActorMethod<[string, string], boolean>,
  'registerStudent' : ActorMethod<[Class, string, string, string], undefined>,
  'rejectApplication' : ActorMethod<[string], undefined>,
  'getAdmissionNumber' : ActorMethod<[string], string>,
  'getAllAdmissionNumbers' : ActorMethod<[], Array<[string, string]>>,
  'rejectApplicationForAdmin' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDraft' : ActorMethod<[string, AdmissionForm], undefined>,
  'submitForm' : ActorMethod<[string, AdmissionForm], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];