/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const Stream = IDL.Variant({
  'arts' : IDL.Null,
  'commerce' : IDL.Null,
  'science' : IDL.Null,
});
export const SubjectSelection = IDL.Record({
  'mil' : IDL.Vec(IDL.Text),
  'sil' : IDL.Vec(IDL.Text),
  'stream' : IDL.Opt(Stream),
  'extraSubjects' : IDL.Opt(IDL.Text),
  'extra' : IDL.Opt(IDL.Text),
  'compulsory' : IDL.Vec(IDL.Text),
});
export const PassingDivision = IDL.Variant({
  'first' : IDL.Null,
  'third' : IDL.Null,
  'second' : IDL.Null,
});
export const BankName = IDL.Variant({
  'other' : IDL.Null,
  'finoPaymentBank' : IDL.Null,
  'dakshinBiharGraminBank' : IDL.Null,
  'indianPostPaymentBank' : IDL.Null,
  'madhyaBiharGraminBank' : IDL.Null,
  'stateBankOfIndia' : IDL.Null,
  'unionBankOfIndia' : IDL.Null,
  'punjabNationalBank' : IDL.Null,
});
export const State = IDL.Variant({ 'bihar' : IDL.Null, 'jharkhand' : IDL.Null });
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Category = IDL.Variant({
  'sc' : IDL.Null,
  'st' : IDL.Null,
  'bci' : IDL.Null,
  'ews' : IDL.Null,
  'bcii' : IDL.Null,
  'general' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AdmissionForm = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'fatherAadhar' : IDL.Text,
  'studentEmail' : IDL.Text,
  'emailId' : IDL.Text,
  'studentName' : IDL.Text,
  'subjects' : SubjectSelection,
  'fathersNameAsPerAadhaar' : IDL.Text,
  'previousSchool' : IDL.Text,
  'ifscCode' : IDL.Text,
  'marksObtained' : IDL.Nat,
  'dateOfBirth' : IDL.Int,
  'eShikshakoshNumber' : IDL.Text,
  'passingYear' : IDL.Nat,
  'apparNumber' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'passingDivision' : PassingDivision,
  'studentPhone' : IDL.Text,
  'studentPen' : IDL.Text,
  'motherName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'mothersOccupation' : IDL.Text,
  'mothersNameAsPerAadhaar' : IDL.Text,
  'fathersName' : IDL.Text,
  'bankName' : BankName,
  'mothersName' : IDL.Text,
  'fathersContact' : IDL.Text,
  'aadharNumber' : IDL.Text,
  'fatherName' : IDL.Text,
  'handicapType' : IDL.Opt(IDL.Text),
  'address' : IDL.Record({
    'policeStation' : IDL.Text,
    'district' : IDL.Text,
    'state' : State,
    'village' : IDL.Text,
    'pinCode' : IDL.Text,
    'block' : IDL.Text,
    'postOffice' : IDL.Text,
  }),
  'gender' : Gender,
  'physicallyHandicapped' : IDL.Bool,
  'mothersContact' : IDL.Text,
  'category' : Category,
  'previousRollNo' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'guardianDeclaration' : IDL.Bool,
  'annualFamilyIncome' : IDL.Text,
  'handicapPercentage' : IDL.Opt(IDL.Nat),
  'motherAadhar' : IDL.Text,
  'fathersOccupation' : IDL.Text,
  'previousExam' : IDL.Text,
});
export const Class = IDL.Variant({
  'class09th' : IDL.Null,
  'class10th' : IDL.Null,
  'class11th' : IDL.Null,
  'class12th' : IDL.Null,
});
export const Time = IDL.Int;
export const Student = IDL.Record({
  'status' : ApplicationStatus,
  'principal' : IDL.Principal,
  'form' : IDL.Opt(AdmissionForm),
  '_class' : Class,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'registrationDate' : Time,
});
export const UserProfile = IDL.Record({
  '_class' : Class,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'isStudent' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveApplication' : IDL.Func([IDL.Text], [], []),
  'approveApplicationForAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllApplicationsForAdmin' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getAllApprovedApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllPendingApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllRejectedApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAdmissionNumber' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getAllAdmissionNumbers' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))], ['query']),
  'getApplicationStatus' : IDL.Func([IDL.Text], [ApplicationStatus], ['query']),
  'getApplicationsSortedByDate' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerStudent' : IDL.Func([], [IDL.Opt(Student)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginStudent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'registerStudent' : IDL.Func([Class, IDL.Text, IDL.Text, IDL.Text], [], []),
  'rejectApplication' : IDL.Func([IDL.Text], [], []),
  'rejectApplicationForAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDraft' : IDL.Func([IDL.Text, AdmissionForm], [], []),
  'submitForm' : IDL.Func([IDL.Text, AdmissionForm], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Stream = IDL.Variant({
    'arts' : IDL.Null,
    'commerce' : IDL.Null,
    'science' : IDL.Null,
  });
  const SubjectSelection = IDL.Record({
    'mil' : IDL.Vec(IDL.Text),
    'sil' : IDL.Vec(IDL.Text),
    'stream' : IDL.Opt(Stream),
    'extraSubjects' : IDL.Opt(IDL.Text),
    'extra' : IDL.Opt(IDL.Text),
    'compulsory' : IDL.Vec(IDL.Text),
  });
  const PassingDivision = IDL.Variant({
    'first' : IDL.Null,
    'third' : IDL.Null,
    'second' : IDL.Null,
  });
  const BankName = IDL.Variant({
    'other' : IDL.Null,
    'finoPaymentBank' : IDL.Null,
    'dakshinBiharGraminBank' : IDL.Null,
    'indianPostPaymentBank' : IDL.Null,
    'madhyaBiharGraminBank' : IDL.Null,
    'stateBankOfIndia' : IDL.Null,
    'unionBankOfIndia' : IDL.Null,
    'punjabNationalBank' : IDL.Null,
  });
  const State = IDL.Variant({ 'bihar' : IDL.Null, 'jharkhand' : IDL.Null });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Category = IDL.Variant({
    'sc' : IDL.Null,
    'st' : IDL.Null,
    'bci' : IDL.Null,
    'ews' : IDL.Null,
    'bcii' : IDL.Null,
    'general' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AdmissionForm = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'fatherAadhar' : IDL.Text,
    'studentEmail' : IDL.Text,
    'emailId' : IDL.Text,
    'studentName' : IDL.Text,
    'subjects' : SubjectSelection,
    'fathersNameAsPerAadhaar' : IDL.Text,
    'previousSchool' : IDL.Text,
    'ifscCode' : IDL.Text,
    'marksObtained' : IDL.Nat,
    'dateOfBirth' : IDL.Int,
    'eShikshakoshNumber' : IDL.Text,
    'passingYear' : IDL.Nat,
    'apparNumber' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'passingDivision' : PassingDivision,
    'studentPhone' : IDL.Text,
    'studentPen' : IDL.Text,
    'motherName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'mothersOccupation' : IDL.Text,
    'mothersNameAsPerAadhaar' : IDL.Text,
    'fathersName' : IDL.Text,
    'bankName' : BankName,
    'mothersName' : IDL.Text,
    'fathersContact' : IDL.Text,
    'aadharNumber' : IDL.Text,
    'fatherName' : IDL.Text,
    'handicapType' : IDL.Opt(IDL.Text),
    'address' : IDL.Record({
      'policeStation' : IDL.Text,
      'district' : IDL.Text,
      'state' : State,
      'village' : IDL.Text,
      'pinCode' : IDL.Text,
      'block' : IDL.Text,
      'postOffice' : IDL.Text,
    }),
    'gender' : Gender,
    'physicallyHandicapped' : IDL.Bool,
    'mothersContact' : IDL.Text,
    'category' : Category,
    'previousRollNo' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'guardianDeclaration' : IDL.Bool,
    'annualFamilyIncome' : IDL.Text,
    'handicapPercentage' : IDL.Opt(IDL.Nat),
    'motherAadhar' : IDL.Text,
    'fathersOccupation' : IDL.Text,
    'previousExam' : IDL.Text,
  });
  const Class = IDL.Variant({
    'class09th' : IDL.Null,
    'class10th' : IDL.Null,
    'class11th' : IDL.Null,
    'class12th' : IDL.Null,
  });
  const Time = IDL.Int;
  const Student = IDL.Record({
    'status' : ApplicationStatus,
    'principal' : IDL.Principal,
    'form' : IDL.Opt(AdmissionForm),
    '_class' : Class,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'registrationDate' : Time,
  });
  const UserProfile = IDL.Record({
    '_class' : Class,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'isStudent' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveApplication' : IDL.Func([IDL.Text], [], []),
    'approveApplicationForAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllApplicationsForAdmin' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getAllApprovedApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllPendingApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllRejectedApplications' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAdmissionNumber' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getAllAdmissionNumbers' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))], ['query']),
    'getApplicationStatus' : IDL.Func(
        [IDL.Text],
        [ApplicationStatus],
        ['query'],
      ),
    'getApplicationsSortedByDate' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerStudent' : IDL.Func([], [IDL.Opt(Student)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [Student], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginStudent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'registerStudent' : IDL.Func([Class, IDL.Text, IDL.Text, IDL.Text], [], []),
    'rejectApplication' : IDL.Func([IDL.Text], [], []),
    'rejectApplicationForAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDraft' : IDL.Func([IDL.Text, AdmissionForm], [], []),
    'submitForm' : IDL.Func([IDL.Text, AdmissionForm], [], []),
  });
};

export const init = ({ IDL }) => { return []; };