/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    _class: Class;
    name: string;
    email: string;
    isStudent: boolean;
}
export type Time = bigint;
export interface SubjectSelection {
    mil: Array<string>;
    sil: Array<string>;
    stream?: Stream;
    extraSubjects?: string;
    extra?: string;
    compulsory: Array<string>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AdmissionForm {
    bankAccountNumber: string;
    fatherAadhar: string;
    studentEmail: string;
    emailId: string;
    studentName: string;
    subjects: SubjectSelection;
    fathersNameAsPerAadhaar: string;
    previousSchool: string;
    ifscCode: string;
    marksObtained: bigint;
    dateOfBirth: bigint;
    eShikshakoshNumber: string;
    passingYear: bigint;
    apparNumber: string;
    accountHolderName: string;
    passingDivision: PassingDivision;
    studentPhone: string;
    studentPen: string;
    motherName: string;
    mobileNumber: string;
    mothersOccupation: string;
    mothersNameAsPerAadhaar: string;
    fathersName: string;
    bankName: BankName;
    mothersName: string;
    fathersContact: string;
    aadharNumber: string;
    fatherName: string;
    handicapType?: string;
    address: {
        policeStation: string;
        district: string;
        state: State;
        village: string;
        pinCode: string;
        block: string;
        postOffice: string;
    };
    gender: Gender;
    physicallyHandicapped: boolean;
    mothersContact: string;
    category: Category;
    previousRollNo: string;
    photo?: ExternalBlob;
    guardianDeclaration: boolean;
    annualFamilyIncome: string;
    handicapPercentage?: bigint;
    motherAadhar: string;
    fathersOccupation: string;
    previousExam: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Student {
    status: ApplicationStatus;
    principal: Principal;
    form?: AdmissionForm;
    _class: Class;
    password: string;
    name: string;
    email: string;
    registrationDate: Time;
}
export enum ApplicationStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected",
    draft = "draft"
}
export enum BankName {
    other = "other",
    finoPaymentBank = "finoPaymentBank",
    dakshinBiharGraminBank = "dakshinBiharGraminBank",
    indianPostPaymentBank = "indianPostPaymentBank",
    madhyaBiharGraminBank = "madhyaBiharGraminBank",
    stateBankOfIndia = "stateBankOfIndia",
    unionBankOfIndia = "unionBankOfIndia",
    punjabNationalBank = "punjabNationalBank"
}
export enum Category {
    sc = "sc",
    st = "st",
    bci = "bci",
    ews = "ews",
    bcii = "bcii",
    general = "general"
}
export enum Class {
    class09th = "class09th",
    class10th = "class10th",
    class11th = "class11th",
    class12th = "class12th"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum PassingDivision {
    first = "first",
    third = "third",
    second = "second"
}
export enum State {
    bihar = "bihar",
    jharkhand = "jharkhand"
}
export enum Stream {
    arts = "arts",
    commerce = "commerce",
    science = "science"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveApplication(email: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllApplications(): Promise<Array<Student>>;
    getAllApprovedApplications(): Promise<Array<Student>>;
    getAllPendingApplications(): Promise<Array<Student>>;
    getAllRejectedApplications(): Promise<Array<Student>>;
    getApplicationStatus(email: string): Promise<ApplicationStatus>;
    getApplicationsSortedByDate(): Promise<Array<Student>>;
    getCallerStudent(): Promise<Student | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getStudent(email: string): Promise<Student>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    loginStudent(email: string, password: string): Promise<boolean>;
    registerStudent(_class: Class, name: string, email: string, password: string): Promise<void>;
    rejectApplication(email: string): Promise<void>;
    rejectApplicationForAdmin(email: string, adminPassword: string): Promise<void>;
    getAllApplicationsForAdmin(adminPassword: string): Promise<Array<Student>>;
    approveApplicationForAdmin(email: string, adminPassword: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDraft(email: string, form: AdmissionForm): Promise<void>;
    submitForm(email: string, form: AdmissionForm): Promise<void>;
}
import type { AdmissionForm as _AdmissionForm, ApplicationStatus as _ApplicationStatus, BankName as _BankName, Category as _Category, Class as _Class, ExternalBlob as _ExternalBlob, Gender as _Gender, PassingDivision as _PassingDivision, State as _State, Stream as _Stream, Student as _Student, SubjectSelection as _SubjectSelection, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveApplication(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveApplication(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllApplications(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllApprovedApplications(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApprovedApplications();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApprovedApplications();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingApplications(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingApplications();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingApplications();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRejectedApplications(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRejectedApplications();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRejectedApplications();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationStatus(arg0: string): Promise<ApplicationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationStatus(arg0);
                return from_candid_ApplicationStatus_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationStatus(arg0);
            return from_candid_ApplicationStatus_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationsSortedByDate(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsSortedByDate();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsSortedByDate();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerStudent(): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStudent();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStudent();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: string): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_Student_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_Student_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginStudent(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.loginStudent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginStudent(arg0, arg1);
            return result;
        }
    }
    async registerStudent(arg0: Class, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(to_candid_Class_n45(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(to_candid_Class_n45(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async rejectApplication(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectApplication(arg0);
            return result;
        }
    }
    async getAllApplicationsForAdmin(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplicationsForAdmin(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplicationsForAdmin(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveApplicationForAdmin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveApplicationForAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveApplicationForAdmin(arg0, arg1);
            return result;
        }
    }
    async rejectApplicationForAdmin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectApplicationForAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectApplicationForAdmin(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDraft(arg0: string, arg1: AdmissionForm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDraft(arg0, await to_candid_AdmissionForm_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDraft(arg0, await to_candid_AdmissionForm_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitForm(arg0: string, arg1: AdmissionForm): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitForm(arg0, await to_candid_AdmissionForm_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitForm(arg0, await to_candid_AdmissionForm_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_AdmissionForm_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdmissionForm): Promise<AdmissionForm> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_BankName_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankName): BankName {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Class_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Class): Class {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PassingDivision_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PassingDivision): PassingDivision {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_State_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _State): State {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Stream_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stream): Stream {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_Student_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Promise<Student> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectSelection_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectSelection): SubjectSelection {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdmissionForm]): Promise<AdmissionForm | null> {
    return value.length === 0 ? null : await from_candid_AdmissionForm_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Stream]): Stream | null {
    return value.length === 0 ? null : from_candid_Stream_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Promise<Student | null> {
    return value.length === 0 ? null : await from_candid_Student_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApplicationStatus;
    principal: Principal;
    form: [] | [_AdmissionForm];
    _class: _Class;
    password: string;
    name: string;
    email: string;
    registrationDate: _Time;
}): Promise<{
    status: ApplicationStatus;
    principal: Principal;
    form?: AdmissionForm;
    _class: Class;
    password: string;
    name: string;
    email: string;
    registrationDate: Time;
}> {
    return {
        status: from_candid_ApplicationStatus_n13(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        form: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.form)),
        _class: from_candid_Class_n37(_uploadFile, _downloadFile, value._class),
        password: value.password,
        name: value.name,
        email: value.email,
        registrationDate: value.registrationDate
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankAccountNumber: string;
    fatherAadhar: string;
    studentEmail: string;
    emailId: string;
    studentName: string;
    subjects: _SubjectSelection;
    fathersNameAsPerAadhaar: string;
    previousSchool: string;
    ifscCode: string;
    marksObtained: bigint;
    dateOfBirth: bigint;
    eShikshakoshNumber: string;
    passingYear: bigint;
    apparNumber: string;
    accountHolderName: string;
    passingDivision: _PassingDivision;
    studentPhone: string;
    studentPen: string;
    motherName: string;
    mobileNumber: string;
    mothersOccupation: string;
    mothersNameAsPerAadhaar: string;
    fathersName: string;
    bankName: _BankName;
    mothersName: string;
    fathersContact: string;
    aadharNumber: string;
    fatherName: string;
    handicapType: [] | [string];
    address: {
        policeStation: string;
        district: string;
        state: _State;
        village: string;
        pinCode: string;
        block: string;
        postOffice: string;
    };
    gender: _Gender;
    physicallyHandicapped: boolean;
    mothersContact: string;
    category: _Category;
    previousRollNo: string;
    photo: [] | [_ExternalBlob];
    guardianDeclaration: boolean;
    annualFamilyIncome: string;
    handicapPercentage: [] | [bigint];
    motherAadhar: string;
    fathersOccupation: string;
    previousExam: string;
}): Promise<{
    bankAccountNumber: string;
    fatherAadhar: string;
    studentEmail: string;
    emailId: string;
    studentName: string;
    subjects: SubjectSelection;
    fathersNameAsPerAadhaar: string;
    previousSchool: string;
    ifscCode: string;
    marksObtained: bigint;
    dateOfBirth: bigint;
    eShikshakoshNumber: string;
    passingYear: bigint;
    apparNumber: string;
    accountHolderName: string;
    passingDivision: PassingDivision;
    studentPhone: string;
    studentPen: string;
    motherName: string;
    mobileNumber: string;
    mothersOccupation: string;
    mothersNameAsPerAadhaar: string;
    fathersName: string;
    bankName: BankName;
    mothersName: string;
    fathersContact: string;
    aadharNumber: string;
    fatherName: string;
    handicapType?: string;
    address: {
        policeStation: string;
        district: string;
        state: State;
        village: string;
        pinCode: string;
        block: string;
        postOffice: string;
    };
    gender: Gender;
    physicallyHandicapped: boolean;
    mothersContact: string;
    category: Category;
    previousRollNo: string;
    photo?: ExternalBlob;
    guardianDeclaration: boolean;
    annualFamilyIncome: string;
    handicapPercentage?: bigint;
    motherAadhar: string;
    fathersOccupation: string;
    previousExam: string;
}> {
    return {
        bankAccountNumber: value.bankAccountNumber,
        fatherAadhar: value.fatherAadhar,
        studentEmail: value.studentEmail,
        emailId: value.emailId,
        studentName: value.studentName,
        subjects: from_candid_SubjectSelection_n18(_uploadFile, _downloadFile, value.subjects),
        fathersNameAsPerAadhaar: value.fathersNameAsPerAadhaar,
        previousSchool: value.previousSchool,
        ifscCode: value.ifscCode,
        marksObtained: value.marksObtained,
        dateOfBirth: value.dateOfBirth,
        eShikshakoshNumber: value.eShikshakoshNumber,
        passingYear: value.passingYear,
        apparNumber: value.apparNumber,
        accountHolderName: value.accountHolderName,
        passingDivision: from_candid_PassingDivision_n24(_uploadFile, _downloadFile, value.passingDivision),
        studentPhone: value.studentPhone,
        studentPen: value.studentPen,
        motherName: value.motherName,
        mobileNumber: value.mobileNumber,
        mothersOccupation: value.mothersOccupation,
        mothersNameAsPerAadhaar: value.mothersNameAsPerAadhaar,
        fathersName: value.fathersName,
        bankName: from_candid_BankName_n26(_uploadFile, _downloadFile, value.bankName),
        mothersName: value.mothersName,
        fathersContact: value.fathersContact,
        aadharNumber: value.aadharNumber,
        fatherName: value.fatherName,
        handicapType: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.handicapType)),
        address: from_candid_record_n28(_uploadFile, _downloadFile, value.address),
        gender: from_candid_Gender_n31(_uploadFile, _downloadFile, value.gender),
        physicallyHandicapped: value.physicallyHandicapped,
        mothersContact: value.mothersContact,
        category: from_candid_Category_n33(_uploadFile, _downloadFile, value.category),
        previousRollNo: value.previousRollNo,
        photo: record_opt_to_undefined(await from_candid_opt_n35(_uploadFile, _downloadFile, value.photo)),
        guardianDeclaration: value.guardianDeclaration,
        annualFamilyIncome: value.annualFamilyIncome,
        handicapPercentage: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.handicapPercentage)),
        motherAadhar: value.motherAadhar,
        fathersOccupation: value.fathersOccupation,
        previousExam: value.previousExam
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mil: Array<string>;
    sil: Array<string>;
    stream: [] | [_Stream];
    extraSubjects: [] | [string];
    extra: [] | [string];
    compulsory: Array<string>;
}): {
    mil: Array<string>;
    sil: Array<string>;
    stream?: Stream;
    extraSubjects?: string;
    extra?: string;
    compulsory: Array<string>;
} {
    return {
        mil: value.mil,
        sil: value.sil,
        stream: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.stream)),
        extraSubjects: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.extraSubjects)),
        extra: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.extra)),
        compulsory: value.compulsory
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    policeStation: string;
    district: string;
    state: _State;
    village: string;
    pinCode: string;
    block: string;
    postOffice: string;
}): {
    policeStation: string;
    district: string;
    state: State;
    village: string;
    pinCode: string;
    block: string;
    postOffice: string;
} {
    return {
        policeStation: value.policeStation,
        district: value.district,
        state: from_candid_State_n29(_uploadFile, _downloadFile, value.state),
        village: value.village,
        pinCode: value.pinCode,
        block: value.block,
        postOffice: value.postOffice
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    _class: _Class;
    name: string;
    email: string;
    isStudent: boolean;
}): {
    _class: Class;
    name: string;
    email: string;
    isStudent: boolean;
} {
    return {
        _class: from_candid_Class_n37(_uploadFile, _downloadFile, value._class),
        name: value.name,
        email: value.email,
        isStudent: value.isStudent
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "approved" in value ? ApplicationStatus.approved : "rejected" in value ? ApplicationStatus.rejected : "draft" in value ? ApplicationStatus.draft : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    arts: null;
} | {
    commerce: null;
} | {
    science: null;
}): Stream {
    return "arts" in value ? Stream.arts : "commerce" in value ? Stream.commerce : "science" in value ? Stream.science : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    first: null;
} | {
    third: null;
} | {
    second: null;
}): PassingDivision {
    return "first" in value ? PassingDivision.first : "third" in value ? PassingDivision.third : "second" in value ? PassingDivision.second : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    finoPaymentBank: null;
} | {
    dakshinBiharGraminBank: null;
} | {
    indianPostPaymentBank: null;
} | {
    madhyaBiharGraminBank: null;
} | {
    stateBankOfIndia: null;
} | {
    unionBankOfIndia: null;
} | {
    punjabNationalBank: null;
}): BankName {
    return "other" in value ? BankName.other : "finoPaymentBank" in value ? BankName.finoPaymentBank : "dakshinBiharGraminBank" in value ? BankName.dakshinBiharGraminBank : "indianPostPaymentBank" in value ? BankName.indianPostPaymentBank : "madhyaBiharGraminBank" in value ? BankName.madhyaBiharGraminBank : "stateBankOfIndia" in value ? BankName.stateBankOfIndia : "unionBankOfIndia" in value ? BankName.unionBankOfIndia : "punjabNationalBank" in value ? BankName.punjabNationalBank : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bihar: null;
} | {
    jharkhand: null;
}): State {
    return "bihar" in value ? State.bihar : "jharkhand" in value ? State.jharkhand : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sc: null;
} | {
    st: null;
} | {
    bci: null;
} | {
    ews: null;
} | {
    bcii: null;
} | {
    general: null;
}): Category {
    return "sc" in value ? Category.sc : "st" in value ? Category.st : "bci" in value ? Category.bci : "ews" in value ? Category.ews : "bcii" in value ? Category.bcii : "general" in value ? Category.general : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    class09th: null;
} | {
    class10th: null;
} | {
    class11th: null;
} | {
    class12th: null;
}): Class {
    return "class09th" in value ? Class.class09th : "class10th" in value ? Class.class10th : "class11th" in value ? Class.class11th : "class12th" in value ? Class.class12th : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Promise<Array<Student>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Student_n11(_uploadFile, _downloadFile, x)));
}
async function to_candid_AdmissionForm_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdmissionForm): Promise<_AdmissionForm> {
    return await to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_BankName_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankName): _BankName {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_Class_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Class): _Class {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function to_candid_PassingDivision_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PassingDivision): _PassingDivision {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_State_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: State): _State {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_Stream_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream): _Stream {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_SubjectSelection_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubjectSelection): _SubjectSelection {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    _class: Class;
    name: string;
    email: string;
    isStudent: boolean;
}): {
    _class: _Class;
    name: string;
    email: string;
    isStudent: boolean;
} {
    return {
        _class: to_candid_Class_n45(_uploadFile, _downloadFile, value._class),
        name: value.name,
        email: value.email,
        isStudent: value.isStudent
    };
}
async function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankAccountNumber: string;
    fatherAadhar: string;
    studentEmail: string;
    emailId: string;
    studentName: string;
    subjects: SubjectSelection;
    fathersNameAsPerAadhaar: string;
    previousSchool: string;
    ifscCode: string;
    marksObtained: bigint;
    dateOfBirth: bigint;
    eShikshakoshNumber: string;
    passingYear: bigint;
    apparNumber: string;
    accountHolderName: string;
    passingDivision: PassingDivision;
    studentPhone: string;
    studentPen: string;
    motherName: string;
    mobileNumber: string;
    mothersOccupation: string;
    mothersNameAsPerAadhaar: string;
    fathersName: string;
    bankName: BankName;
    mothersName: string;
    fathersContact: string;
    aadharNumber: string;
    fatherName: string;
    handicapType?: string;
    address: {
        policeStation: string;
        district: string;
        state: State;
        village: string;
        pinCode: string;
        block: string;
        postOffice: string;
    };
    gender: Gender;
    physicallyHandicapped: boolean;
    mothersContact: string;
    category: Category;
    previousRollNo: string;
    photo?: ExternalBlob;
    guardianDeclaration: boolean;
    annualFamilyIncome: string;
    handicapPercentage?: bigint;
    motherAadhar: string;
    fathersOccupation: string;
    previousExam: string;
}): Promise<{
    bankAccountNumber: string;
    fatherAadhar: string;
    studentEmail: string;
    emailId: string;
    studentName: string;
    subjects: _SubjectSelection;
    fathersNameAsPerAadhaar: string;
    previousSchool: string;
    ifscCode: string;
    marksObtained: bigint;
    dateOfBirth: bigint;
    eShikshakoshNumber: string;
    passingYear: bigint;
    apparNumber: string;
    accountHolderName: string;
    passingDivision: _PassingDivision;
    studentPhone: string;
    studentPen: string;
    motherName: string;
    mobileNumber: string;
    mothersOccupation: string;
    mothersNameAsPerAadhaar: string;
    fathersName: string;
    bankName: _BankName;
    mothersName: string;
    fathersContact: string;
    aadharNumber: string;
    fatherName: string;
    handicapType: [] | [string];
    address: {
        policeStation: string;
        district: string;
        state: _State;
        village: string;
        pinCode: string;
        block: string;
        postOffice: string;
    };
    gender: _Gender;
    physicallyHandicapped: boolean;
    mothersContact: string;
    category: _Category;
    previousRollNo: string;
    photo: [] | [_ExternalBlob];
    guardianDeclaration: boolean;
    annualFamilyIncome: string;
    handicapPercentage: [] | [bigint];
    motherAadhar: string;
    fathersOccupation: string;
    previousExam: string;
}> {
    return {
        bankAccountNumber: value.bankAccountNumber,
        fatherAadhar: value.fatherAadhar,
        studentEmail: value.studentEmail,
        emailId: value.emailId,
        studentName: value.studentName,
        subjects: to_candid_SubjectSelection_n51(_uploadFile, _downloadFile, value.subjects),
        fathersNameAsPerAadhaar: value.fathersNameAsPerAadhaar,
        previousSchool: value.previousSchool,
        ifscCode: value.ifscCode,
        marksObtained: value.marksObtained,
        dateOfBirth: value.dateOfBirth,
        eShikshakoshNumber: value.eShikshakoshNumber,
        passingYear: value.passingYear,
        apparNumber: value.apparNumber,
        accountHolderName: value.accountHolderName,
        passingDivision: to_candid_PassingDivision_n55(_uploadFile, _downloadFile, value.passingDivision),
        studentPhone: value.studentPhone,
        studentPen: value.studentPen,
        motherName: value.motherName,
        mobileNumber: value.mobileNumber,
        mothersOccupation: value.mothersOccupation,
        mothersNameAsPerAadhaar: value.mothersNameAsPerAadhaar,
        fathersName: value.fathersName,
        bankName: to_candid_BankName_n57(_uploadFile, _downloadFile, value.bankName),
        mothersName: value.mothersName,
        fathersContact: value.fathersContact,
        aadharNumber: value.aadharNumber,
        fatherName: value.fatherName,
        handicapType: value.handicapType ? candid_some(value.handicapType) : candid_none(),
        address: to_candid_record_n59(_uploadFile, _downloadFile, value.address),
        gender: to_candid_Gender_n62(_uploadFile, _downloadFile, value.gender),
        physicallyHandicapped: value.physicallyHandicapped,
        mothersContact: value.mothersContact,
        category: to_candid_Category_n64(_uploadFile, _downloadFile, value.category),
        previousRollNo: value.previousRollNo,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n66(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        guardianDeclaration: value.guardianDeclaration,
        annualFamilyIncome: value.annualFamilyIncome,
        handicapPercentage: value.handicapPercentage ? candid_some(value.handicapPercentage) : candid_none(),
        motherAadhar: value.motherAadhar,
        fathersOccupation: value.fathersOccupation,
        previousExam: value.previousExam
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mil: Array<string>;
    sil: Array<string>;
    stream?: Stream;
    extraSubjects?: string;
    extra?: string;
    compulsory: Array<string>;
}): {
    mil: Array<string>;
    sil: Array<string>;
    stream: [] | [_Stream];
    extraSubjects: [] | [string];
    extra: [] | [string];
    compulsory: Array<string>;
} {
    return {
        mil: value.mil,
        sil: value.sil,
        stream: value.stream ? candid_some(to_candid_Stream_n53(_uploadFile, _downloadFile, value.stream)) : candid_none(),
        extraSubjects: value.extraSubjects ? candid_some(value.extraSubjects) : candid_none(),
        extra: value.extra ? candid_some(value.extra) : candid_none(),
        compulsory: value.compulsory
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    policeStation: string;
    district: string;
    state: State;
    village: string;
    pinCode: string;
    block: string;
    postOffice: string;
}): {
    policeStation: string;
    district: string;
    state: _State;
    village: string;
    pinCode: string;
    block: string;
    postOffice: string;
} {
    return {
        policeStation: value.policeStation,
        district: value.district,
        state: to_candid_State_n60(_uploadFile, _downloadFile, value.state),
        village: value.village,
        pinCode: value.pinCode,
        block: value.block,
        postOffice: value.postOffice
    };
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Class): {
    class09th: null;
} | {
    class10th: null;
} | {
    class11th: null;
} | {
    class12th: null;
} {
    return value == Class.class09th ? {
        class09th: null
    } : value == Class.class10th ? {
        class10th: null
    } : value == Class.class11th ? {
        class11th: null
    } : value == Class.class12th ? {
        class12th: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream): {
    arts: null;
} | {
    commerce: null;
} | {
    science: null;
} {
    return value == Stream.arts ? {
        arts: null
    } : value == Stream.commerce ? {
        commerce: null
    } : value == Stream.science ? {
        science: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PassingDivision): {
    first: null;
} | {
    third: null;
} | {
    second: null;
} {
    return value == PassingDivision.first ? {
        first: null
    } : value == PassingDivision.third ? {
        third: null
    } : value == PassingDivision.second ? {
        second: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankName): {
    other: null;
} | {
    finoPaymentBank: null;
} | {
    dakshinBiharGraminBank: null;
} | {
    indianPostPaymentBank: null;
} | {
    madhyaBiharGraminBank: null;
} | {
    stateBankOfIndia: null;
} | {
    unionBankOfIndia: null;
} | {
    punjabNationalBank: null;
} {
    return value == BankName.other ? {
        other: null
    } : value == BankName.finoPaymentBank ? {
        finoPaymentBank: null
    } : value == BankName.dakshinBiharGraminBank ? {
        dakshinBiharGraminBank: null
    } : value == BankName.indianPostPaymentBank ? {
        indianPostPaymentBank: null
    } : value == BankName.madhyaBiharGraminBank ? {
        madhyaBiharGraminBank: null
    } : value == BankName.stateBankOfIndia ? {
        stateBankOfIndia: null
    } : value == BankName.unionBankOfIndia ? {
        unionBankOfIndia: null
    } : value == BankName.punjabNationalBank ? {
        punjabNationalBank: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: State): {
    bihar: null;
} | {
    jharkhand: null;
} {
    return value == State.bihar ? {
        bihar: null
    } : value == State.jharkhand ? {
        jharkhand: null
    } : value;
}
function to_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    sc: null;
} | {
    st: null;
} | {
    bci: null;
} | {
    ews: null;
} | {
    bcii: null;
} | {
    general: null;
} {
    return value == Category.sc ? {
        sc: null
    } : value == Category.st ? {
        st: null
    } : value == Category.bci ? {
        bci: null
    } : value == Category.ews ? {
        ews: null
    } : value == Category.bcii ? {
        bcii: null
    } : value == Category.general ? {
        general: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
